<?xml version="1.0"?>
<package format="3">
  <name>mobile_manipulator_description</name>
  <version>0.0.1</version>
  <description>Combined TurtleBot3 Waffle and Doosan A0912 mobile manipulator description.</description>

  <maintainer email="smudhan@example.com">Shubham Udhan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>turtlebot3_description</exec_depend>
  <exec_depend>my_doosan_pkg</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>